services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile

    image: playwright-test-image

    container_name: playwright-test-container

    working_dir: /app

    volumes:
      - .:/app

    command: npx playwright test